### ISSUE TITLE
OpenSAP contribution in Python

### ISSUE THREAD

**Issue by AmauryVanEspen** [ceedee666/opensap_python_intro#4]
Hello
it seems to be this is a great initiative,
I would be interested in setting up a common "hands-on" project.
I've open a repo about creating an API for OpenSAP certification.
We could set up together an step by step Python tutorial for https://developers.sap.com related to webscrap the https://open.sap.com/courses page, get the title of the courses then provide an API, maybe through Flask in order to provide a list of the available courses and certification as well as from the https://people.sap.com profile and to feed the various LMS platform (successfactor, workday etc ...)
please see : [Github repository](https://github.com/AmauryVanEspen/OpenSAP-certification-API)
The target could be something similar to [traning certification validity list](https://training.sap.com/certification/validity) with API endpoint. Let's ask @jung-thomas and @qmacro their interest or the person in charge to start such an initiative.
Regards
Amaury

**Comment by ceedee666** [comment]
Hi @AmauryVanEspen,
tanks for reaching out. Sounds like an interesting idea. However, right now i can't commit to participate. I currently need to get the OpenSAP Python introduction finished (i.e. this course). Furthermore, I need to finalize the S/4HANA course book I'm working on. After that (spring  next year) I would be open for new projects. 
Christian
